### ISSUE TITLE
Are some code files missing from your project?

### ISSUE THREAD

**Issue by q993968980** [mrinmoy-iitg/Speech-Music-Classification-Using-SPT#1]
I am following your project to replicate your experiment and found that the files computepeaktracs.py, feature_computation. py and compute_cbow_features.py in the configuration file configuration.ini did not appear in your project. Could you please upload these files to replicate your experiment?

![QQ图片20210408090904](https://user-images.githubusercontent.com/56919415/113953292-13ac6880-984a-11eb-9486-081bef71746a.png)

**Comment by mrinmoy-iitg** [comment]
Updated the repo
